SHOW DATABASES;

USE KPAY;

CREATE TABLE TB_MONEY_SPREADING (
	SPREADING_ID 	INT 		NOT NULL	AUTO_INCREMENT
    ,USER_ID		INT			NOT NULL
    ,ROOM_ID		VARCHAR(20)	NOT NULL
    ,MONEY_AMOUNT	int			NOT NULL
    ,TOKEN			CHAR(3)		NOT NULL
    ,SPREADING_DTTM DATETIME	NOT NULL
    ,REG_EMNO		VARCHAR(20)	NOT NULL
    ,REG_DTTM		DATETIME	NOT NULL
	,MODI_EMNO		VARCHAR(20)	NOT NULL
    ,MODI_DTTM		DATETIME	
    ,PRIMARY KEY(SPREADING_ID)
);

CREATE TABLE TB_MONEY_SPREADING_RESULT (
	SPREADING_RESULT_ID		INT			NOT NULL	AUTO_INCREMENT
	,SPREADING_ID			INT			NOT NULL
	,MONEY_AMOUNT			INT			NOT NULL
	,USER_ID				int			
	,RECEIVED_DTTM			DATETIME	
	,REG_EMNO				VARCHAR(20)	NOT NULL
	,REG_DTTM				DATETIME	NOT NULL
	,MODI_EMNO				VARCHAR(20)	NOT NULL
	,MODI_DTTM				DATETIME	
    ,PRIMARY KEY(SPREADING_RESULT_ID)
    ,FOREIGN KEY(SPREADING_ID)
    REFERENCES TB_MONEY_SPREADING(SPREADING_ID) ON UPDATE CASCADE
);
 
ALTER TABLE TB_MONEY_SPREADING AUTO_INCREMENT = 0;
ALTER TABLE TB_MONEY_SPREADING_RESULT AUTO_INCREMENT = 0;

DROP TABLE TB_MONEY_SPREADING;
DROP TABLE TB_MONEY_SPREADING_RESULT;