drop table TB_MONEY_SPREADING;
drop table TB_MONEY_SPREADING_RESULT;

show databases;
use kpay;
show tables;

ALTER TABLE TB_MONEY_SPREADING AUTO_INCREMENT = 1;
ALTER TABLE TB_MONEY_SPREADING_RESULT AUTO_INCREMENT = 1;

select * from TB_MONEY_SPREADING;
select * from TB_MONEY_SPREADING_RESULT;

CREATE TABLE TB_MONEY_SPREADING (
	SPREADING_ID 	INT 		NOT NULL	AUTO_INCREMENT
    ,TOKEN			CHAR(3)		NOT NULL
    ,USER_ID		INT			NOT NULL
    ,ROOM_ID		VARCHAR(20)	NOT NULL
    ,MONEY_AMOUNT	INT			NOT NULL
    ,USER_COUNT		INT			NOT NULL
    ,SPREADING_DTTM DATETIME	NOT NULL DEFAULT NOW()
    ,REG_EMNO		VARCHAR(20)	NOT NULL DEFAULT 'KPAY'
    ,REG_DTTM		DATETIME	NOT NULL DEFAULT NOW()
	,MODI_EMNO		VARCHAR(20)	NOT NULL DEFAULT 'KPAY'
    ,MODI_DTTM		DATETIME	NOT NULL DEFAULT NOW()
	,CMPE_YN		CHAR(1)		NOT NULL DEFAULT 'N'
    ,PRIMARY KEY(SPREADING_ID)
);

CREATE TABLE TB_MONEY_SPREADING_RESULT (
	SPREADING_RESULT_ID		INT			NOT NULL	AUTO_INCREMENT
	,SPREADING_ID			INT			NOT NULL
	,MONEY_AMOUNT			INT			NOT NULL
	,USER_ID				INT			
	,RECEIVED_DTTM			DATETIME	
	,REG_EMNO				VARCHAR(20)	NOT NULL DEFAULT 'KPAY'
	,REG_DTTM				DATETIME	NOT NULL DEFAULT NOW()
	,MODI_EMNO				VARCHAR(20)	NOT NULL DEFAULT 'KPAY'	 	
	,MODI_DTTM				DATETIME	NOT NULL DEFAULT NOW()
    ,CMPE_YN				CHAR(1)		NOT NULL DEFAULT 'N'
    ,PRIMARY KEY(SPREADING_RESULT_ID)
    ,FOREIGN KEY(SPREADING_ID)
    REFERENCES TB_MONEY_SPREADING(SPREADING_ID) ON UPDATE CASCADE
);